--CloudOps Cost & Reliability Guardrails (V1 SQL Schema)
--Postgre schema: Source of Truth for State + History

Begin;

--UUID Generation (EX. gen_random_uuid())
Create EXTENSION IF NOT EXISTS pgcrypto;

-- =========================
-- projects
-- =========================

CREATE TABLE IF NOT EXISTS projects (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name        TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW ()
);

-- =========================
-- daily_costs
-- One row per (project, date, service)
-- =========================

CREATE TABLE IF NOT EXISTS daily_costs (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,

    cost_date   DATE NOT NULL,
    service     TEXT NOT NULL,

    amount      NUMERIC(12,4) NOT NULL CHECK (amount >=0),
    currency    TEXT NOT NULL DEFAULT 'USD',

    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_daily_costs_project_date_service
        UNIQUE (project_id, cost_date, service)
);

-- Helful for last-30-days charts and service breakdowns
CREATE INDEX IF NOT EXISTS idx_daily_costs_project_date
    ON daily_costs (project_id, cost_date);

CREATE INDEX IF NOT EXISTS idx_daily_costs_project_service_date
    ON daily_costs (project_id, service, cost_date);

-- =========================
-- reliability_metrics
-- One row per (project, timestamp, metric_name)
-- =========================

CREATE TABLE IF NOT EXISTS reliability_metrics (
    id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id  UUID NOT FULL NULL REFERENCES projects(id) ON DELETE CASCADE,

    metric_ts   TIMESTAMPTZ NOT NULL,
    metric_name TEXT NOT NULL CHECK (metric_name IN ('5xx_count', 'p95_latency_ms')),
    value       NUMERIC(16, 6) NOT NULL,
    unit        TEXT NOT NULL, --e.x. 'count', 'ms'

    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_reliability_project_ts_metric
        UNIQUE (project_id, metric_ts, metric_name)
);

CREATE INDEX IF NOT EXISTS idx_reliability_project_ts
    ON reliability_metrics (project_id, metric_ts);

CREATE INDEX IF NOT EXISTS idx_reliability_project_metric_ts
    ON reliability_metrics (project_id, metric_name, metric_ts);

-- =========================
-- alerts
-- Workflow object generated by guardrails logic
-- =========================

CREATE TABLE IF NOT EXISTS alerts (
    id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,

    alert_type  TEXT NOT NULL CHECK (alert_type IN ('cost', 'reliability')),
    status      TEXT NOT NULL CHECK (status IN('open', 'achknowledged', 'resolved')),
    severity    TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high')),

    title       TEXT NOT NULL,
    description TEXT NOT NULL,

    source      TEXT NOT NULL, --ex 'cost explorer', 'cloudwatch', 'etc'

    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    window_start TIMESTAMPTZ NULL,
    window_end   TIMESTAMPTZ NULL,

    --Explination Fields (NULL because cost & reliability alerts differ in meaning)
    service_name   TEXT NULL, --for cost alerts variables
    metric_name    TEXT NULL, -- for reliablity alerts ('5xx_count', 'p95_latency_ms')

    observed_value  NUMERIC(16, 6) NULL,
    baseline_value  NUMERIC(16, 6) NULL,
    threshold_value NUMERIC(16,6)  NULL,

    rule_name      TEXT NOT NULL, --simple strings like 'daily_service_cost'

    achknowledged_at    TIMESTAMPTZ NULL,
    resolved_at         TIMESTAMPTZ NULL,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW (),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW (),
);

-- Common UI queries: open alerts, latest served first

CREATE INDEX IF NOT EXISTS idx_alerts_project_status_detected
    ON alerts (project_id, status, detected_at DESC);

CREATE INDEX IF NOT EXISTS idx_alerts_project_type_detected
    ON alerts (project_id, alert_type, detected_at DESC);

--Optional: helps in searching cost alerts by AWS Service

CREATE INDEX IF NOT EXISTS idx_alerts_project_service_detected
    ON alerts (project_id, service_name, detected_at DESC);

--=====================
--reccomendations 
--Action generated from alerts; status in user-managed
--=====================

CREATE TABLE IF NOT EXISTS reccomendations (
    id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    project_id  UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    alert_id    UUID NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,

    status  TEXT NOT NULL CHECK (status IN ('open', 'in_progress', 'done', 'dissmissed')),

    title           TEXT NOT NULL,
    action_steps    TEXT NOT NULL,
    impact          TEXT NOT NULL,

    owner           TEXT NULL, --optional feature for V1 Release (email?)

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    done_at         TIMESTAMPTZ NULL,
    dissmissed_at   TIMESTAMPTZ NULL,
);

CREATE INDEX IF NOT EXISTS idx_recos_alert
    ON reccomendations (alert_id);

CREATE INDEX IF NOT EXISTS idx_recos_project_status_updated
    ON reccomendations (project_id, status, updated at DESC);


-- =========================
-- events
-- Audit trail / history log
-- =========================

CREATE TABLE IF NOT EXISTS events (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id   UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,

  entity_type  TEXT NOT NULL CHECK (entity_type IN ('alert', 'recommendation', 'job')),
  entity_id    UUID NULL, -- for 'job' events this is NULL

  event_type   TEXT NOT NULL, -- e.g. 'created', 'status_changed', 'ingested', 'job_run'
  message      TEXT NOT NULL,

  actor        TEXT NOT NULL DEFAULT 'system', -- 'system' or user email
  metadata     JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_events_entity_timeline
  ON events (entity_type, entity_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_events_project_created
  ON events (project_id, created_at DESC);

COMMIT;